### ISSUE TITLE
Distributive Property over Booleans

### ISSUE THREAD

**Issue by blogle** [learnyou/lysa-pdfs#1]
I might be wrong, but wouldn't the distributive be 
![gif](https://cloud.githubusercontent.com/assets/4959802/7280347/fbd09854-e8ef-11e4-8c4a-a0ad7219699f.gif)

Not 
![gif](https://cloud.githubusercontent.com/assets/4959802/7280359/1b898ce6-e8f0-11e4-98a7-d02f10db67ed.gif)

**Comment by pharpend** [comment]
Yes, you're right. Sorry I'm late to the party, I didn't get a notification on this.

**Comment by pharpend** [comment]
I fixed this in the source. You should see the result in the next nightly.
